[GLOBAL]
pants_version = "2.13.0"
backend_packages = [
	"pants.backend.python",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.lint.pylint",
	"pants.backend.python.typecheck.mypy"
]

[source]
root_patterns = [
	"/",
	"lilatomic/azcli",
	"lilatomic/api",
]

[pylint]
config = ".pylintrc"
[flake8]
config = ".flake8"

[test]
use_coverage = true

[coverage-py]
report = ["xml", "html"]

[mypy]
extra_type_stubs = ["types-PyYAML", "types-requests"]
config = "mypy.ini"
