[GLOBAL]
pants_version = "2.15.0rc6"
backend_packages = [
	"pants.backend.python",
	"pants.backend.experimental.python",
	"pants.backend.python.lint.black",
	"pants.backend.python.lint.isort",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.lint.pylint",
	"pants.backend.python.typecheck.mypy",
	"pants.backend.build_files.fmt.black",
]

[source]
root_patterns = [
	"/ansibles",
	"/tools",
]

[python]
enable_resolves = true
default_resolve = "tools"

[python.resolves]
"tools" = "cicd/tools.lock"
"ansible.lilatomic.azcli" = "cicd/ansible.lilatomic.azcli.lock"
"ansible.lilatomic.api" = "cicd/ansible.lilatomic.api.lock"

[pylint]
config = ".pylintrc"

[flake8]
config = ".flake8"

[black]
args = ["--use-tabs"]
console_script = "tan"
version = "tan==21.14"
lockfile = "cicd/tan.lockfile"
extra_requirements = ["click!=8.1.*", "typing-extensions>=3.10.0.0"]

[test]
use_coverage = true

[coverage-py]
report = ["xml", "html"]

[mypy]
lockfile = "cicd/mypy.lock"

extra_requirements.add = ["pytest"]
extra_type_stubs = ["types-PyYAML", "types-requests"]

[anonymous-telemetry]
enabled = true
repo_id = "aa6f686d-ffa7-35a8-99c9-37a1a61e8f67"
