---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: my-deployment
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: testchart
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: testchart-0.1.0
    my-label: my-label-value
  name: my-deployment-testchart
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: my-deployment
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: testchart
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: testchart-0.1.0
    my-label: my-label-value
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
  name: my-deployment-testchart
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: my-deployment
    app.kubernetes.io/name: testchart
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: my-deployment
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: testchart
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: testchart-0.1.0
    my-label: my-label-value
  name: my-deployment-testchart
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-deployment
      app.kubernetes.io/name: testchart
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: my-deployment
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: testchart
        app.kubernetes.io/version: 1.16.0
        helm.sh/chart: testchart-0.1.0
    spec:
      containers:
      - image: nginx:1.16.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: testchart
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
      serviceAccountName: my-deployment-testchart
