name: Ansible

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        collection: ["lilatomic/azcli", "lilatomic/api"]
#        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r ansibles/${{ matrix.collection }}/requirements.txt

      - name: Run ansible-test sanity
        run: |
          mkdir -p /tmp/ansible_collections/${{ matrix.collection }}
          cp -r ansibles/${{ matrix.collection }}/* /tmp/ansible_collections/${{ matrix.collection }}/
          
          pushd /tmp/ansible_collections/${{ matrix.collection }}
          ansible-test sanity --requirements \
            --skip-test import \
            --skip-test pslint \
            --skip-test pep8 \
            --skip-test metaclass-boilerplate \
            --skip-test future-import-boilerplate \
            --skip-test action-plugin-docs \
            --skip-test validate-modules
        if: success() || failure()

      - name: Run ansible-test units
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: "stable-2.13"
          testing-type: units
          collection-root: ansibles/${{ matrix.collection }}
        if: success() || failure()
      - run: |
          rm -r ansible_collections/${{ matrix.collection }}
        if: success() || failure()

      - name: Run ansible-test integration
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          pre-test-cmd: pip3 install -r requirements.txt
          ansible-core-version: "stable-2.13"
          testing-type: integration
          collection-root: ansibles/${{ matrix.collection }}
        if: success() || failure()
      - run: |
          rm -r ansible_collections/${{ matrix.collection }}
        if: success() || failure()
