python_sources(
	sources=["plugins/**/*.py"],
	resolve="ansible.lilatomic.api",
)

python_requirements(
	name="reqs",
	module_mapping={"ansible-core": ["ansible"]},
	resolve="ansible.lilatomic.api",
)
